language: python
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
sudo: required
install:
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
before_script:
  - sudo docker-compose -f docker-compose.yml up --d
script:
  - nosetests
after_script:
  - docker-compose down
deploy:
  provider: heroku
  api_key: 0c8b9e98-a72b-4e0a-b091-568f4d4186e0
  app:
    development: gicsaude
    master: gerenciamais
