sudo: required

language: python
python:
  - "3.6.4"
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo pip install docker-compose
  - pip install -r requirements.txt
before_script:
  - sudo docker-compose -f docker-compose.yml up --d


script:
  - python manage.py makemigrations --noinput
  - python manage.py migrate
  - coverage run -m django test --settings=tests.settings
  - docker-compose down

after_success:
  - coveralls

after_script:
  - docker-compose down

deploy:
  provider: heroku
  api_key: "oDBJRn9eew6RdKlRfMETFnZ0qTqwk7leCt/TLf38C8eQjfkIs9lA85x8XX9OWPI+mi2pgErWtyuz29hXx6DDuewFcikqEmS/Ifb8ht8K9z74v9FdVYbExWDsCKFBgE1H4IV6zkQrZa/NXvxxOO66KLPr8SmEKurj6SIiT1NzC+xsxrOwdaPlJTRE4leLQGNji0IYBdrmd2IXYRXlduxSr3J7kDomKRTxSwquGlyOEwfwk/+r7RQD1rQajfGlI3yL0EkI7KgUqKrFWzl3/hQKiJBWqQ5ZLYGYIA4s0GorpQbdwhzTHTBYFLhI44ZqRRVanJGBKCWA+u9sn955uQ0xZiDH/mmPuYqBLsVnAVb/GGX64MoeOA7ee5uw0A+H1dyrqSVYxND/C0UTHPydVjSFt+tu1Z6co2FqXuin0YqeRKYY4c5daBjTkSl3zQujfzIGm0zkRUMvogmjUmWbU72lkWac1aOmBUjZKJBtbKzsT4vhTfWPMnVkJQPsWVE3Gt6FpHnQRip+Xk2yM5YiCgA2wHFttrbcsOVNbM+ZqZonhKsmocInrY/92n+rAG9q5/hxBmTeDcn49ISd82CaEBYTH2DY7D4sX6z0fzPQ1T+8qeNBmr5qN1HLgCzEFdbrbloVVna+2fEqmpzw/VgA6ZcJms2DZavAC+7Ay9y4PaiGmVI="
  app:
    development: gicsaude
    master: gerenciamais
