site_name: Gerencia mais

theme:
  name: 'jekyll-theme-slate'

pages:
    - Home: README.md

    - EPS:
        - Termo de abertura do projeto: documentos/Eps/Termo_de_abertura_do_Projeto.md


    - MDS:
        - Documento de visão: documentos/Mds/Elicitacao/Documento_de_Visao.md
